FROM build:build

WORKDIR /usr/src/ServerGRPCTest
COPY . /usr/src/ServerGRPCTest

# Generate gRPC protobuf files
WORKDIR /usr/src/ServerGRPCTest
RUN ./grpc_file_generation.sh

# Make the application - build type Release
RUN mkdir build && cd build && cmake .. && make -j4 ServerGRPCTest
